### ISSUE TITLE
Will the author open source code ?

### ISSUE THREAD

**Issue by Nefertarier** [ridiculouz/TaG#2]
I am very interested in your work, would like to ask the author will also open source?

**Comment by ridiculouz** [comment]
Thanks for your interest, and ofc we will open-source our code! But I've been personally occupied recently, so it will take some time to revise the code when available. Optimistically it will go public this month.

**Comment by WatsonWangZh** [comment]
Will you open source code this month?

**Comment by ridiculouz** [comment]
Hi there,
Sorry for the delay, we have uploaded the tested code to the current repository.
