### ISSUE TITLE
Will you open the code ?

### ISSUE THREAD

**Issue by jdelaunay** [ridiculouz/TaG#5]
Dear authors,
I read your article with great interest, especially as this is unfortunately a fairly shallow domain of research.
Do you plan to release your code, as indicated in the article, and when ?

Sincerely yours,

**Comment by lsvih** [comment]
@jdelaunay Hi there, I have urged the first author to upload the code, and he has stated that he will tidy it up and upload code ASAP. 
So sorry for our delay. 🙏

**Comment by ridiculouz** [comment]
Hi there,
Sorry for the delay, we have uploaded the tested code to the current repository.
