### ISSUE TITLE
关于num_rel

### ISSUE THREAD

**Issue by Nefertarier** [ridiculouz/TaG#7]

**Comment by Nefertarier** [comment]
您好，想问下为什么您在modol.py中将num_rel的值设置为3，据我了解DocRED数据集中的关系数量为97，对此我感到很困惑。
![6393a20c14c0ef5d84f013b73b598ce](https://github.com/ridiculouz/TaG/assets/72508413/c4f22865-8ad0-4b1a-8b33-494c12c13c7b)

**Comment by ridiculouz** [comment]
您好，
RGCN这里的num_rel指的是channel的数量，即rel/coref/syntax三种边。rel/coref构边的时候在coarse-level是做0/1预测的，论文里应该也有提到，可以再看一下。

祝好
